//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public long id { get; set; }
        public int need_amount { get; set; }
        public int percent { get; set; }
        public long product_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
